### ISSUE TITLE
Issue with loading SnFFT package

### ISSUE THREAD

**Issue by saurabh08** [GDPlumb/SnFFT.jl#2]
There seems to be issue in initial setup of SnFFT package. Any suggestions on how to fix it.
 
julia> using SnFFT

WARNING: deprecated syntax "for (...)" at /home/saurabh/.julia/v0.5/SnFFT/src/Examples.jl:210.
Use "for ..." instead.
WARNING: Method definition nextidx() in module SnFFT at /home/saurabh/.julia/v0.5/SnFFT/src/FFT.jl:32 overwritten at /home/saurabh/.julia/v0.5/SnFFT/src/FFT.jl:63.
ERROR: LoadError: LoadError: ArgumentError: invalid type for argument RR_YOR in method definition for compute_fft_remote at /home/saurabh/.julia/v0.5/SnFFT/src/FFT.jl:114
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
while loading /home/saurabh/.julia/v0.5/SnFFT/src/FFT.jl, in expression starting on line 113
while loading /home/saurabh/.julia/v0.5/SnFFT/src/SnFFT.jl, in expression starting on line 9

**Comment by GDPlumb** [comment]
I think that the "RemoteRef" object type is no longer defined in Julia v0.5

A quick look at the documentation shows that replacing them with a Future type may solve the problem.  

Does that help?  (I'm not using v0.5)

**Comment by saurabh08** [comment]
Thanks!. Replacing "RemoteRef" by "RemoteChannel" seems to work in Julia v0.5.
